version: '3.1'

services:
    flowise:
        image: flowiseai/flowise
        restart: always
        environment:
            - PORT=3000
            - FLOWISE_USERNAME=gobillion
            - FLOWISE_PASSWORD=ai@experiment
        ports:
            - '3000:3000'
        volumes:
            - ~/.flowise:/root/.flowise
        command: /bin/sh -c "sleep 3; flowise start"
